kind: ImageStreamList
apiVersion: image.openshift.io/v1
metadata:
  name: rhdm713-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Decision Manager 7.13
    openshift.io/provider-display-name: Red Hat, Inc.
items:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: rhdm-decisioncentral-rhel8
      annotations:
        openshift.io/display-name: Red Hat Decision Manager Decision Central 7.13
        openshift.io/provider-display-name: Red Hat, Inc.
    spec:
      tags:
        - name: '7.13.0'
          annotations:
            description: Red Hat Decision Manager 7.13 - Decision Central image.
            iconClass: icon-jboss
            tags: rhdm
            supports: rhdm:7.13
            version: '7.13.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.13.0
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: rhdm-controller-rhel8
      annotations:
        openshift.io/display-name: Red Hat Decision Manager Standalone Controller 7.13
        openshift.io/provider-display-name: Red Hat, Inc.
    spec:
      tags:
        - name: '7.13.0'
          annotations:
            description: Red Hat Decision Manager 7.13 - Standalone Controller image.
            iconClass: icon-jboss
            tags: rhdm
            supports: rhdm:7.13
            version: '7.13.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: registry.redhat.io/rhdm-7/rhdm-controller-rhel8:7.13.0
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: rhdm-kieserver-rhel8
      annotations:
        openshift.io/display-name: Red Hat Decision Manager KIE Server 7.13
        openshift.io/provider-display-name: Red Hat, Inc.
    spec:
      tags:
        - name: '7.13.0'
          annotations:
            description: Red Hat Decision Manager 7.13 - KIE Server image.
            iconClass: icon-jboss
            tags: rhdm
            supports: rhdm:7.13
            version: '7.13.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.13.0
