kind: ImageStreamList
apiVersion: v1
metadata:
  name: rhdm73-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Decision Manager 7.3
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm73-decisioncentral-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Decision Central 7.3
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.3 - Decision Central image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.3
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm73-decisioncentral-openshift:1.0
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm73-controller-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Standalone Controller 7.3
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.3 - Standalone Controller image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.3
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm73-controller-openshift:1.0
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm73-kieserver-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager KIE Server 7.3
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.3 - KIE Server image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.3
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm73-kieserver-openshift:1.0
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm73-decisioncentral-indexing-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Decision Central Indexing 7.3
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.3 - Decision Central Indexing image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.3
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7-tech-preview/rhdm73-decisioncentral-indexing-openshift:1.0
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm73-optaweb-employee-rostering-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Business Optimizer OptaWeb Employee Rostering 7.3
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.3 - Business Optimizer OptaWeb Employee Rostering image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.3
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7-tech-preview/rhdm73-optaweb-employee-rostering-openshift:1.0
