---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-jboss
    tags: rhdm,jboss,xpaas,optaweb,employee-rostering
    version: "1.0"
    openshift.io/display-name: Ephemeral Red Hat Decision Manager Employee Rostering Optimizer 7.1 which uses an external DB.
    openshift.io/provider-display-name: Red Hat, Inc.
    description: Application template for Red Hat Decision Manager Employee Rostering Optimizer 7.1 which uses an external DB.
    template.openshift.io/long-description: This template defines resources needed to install the Red Hat Business Automation Employee Rostering Optimizer application, including application deployment configuration, secure and insecure http communication and persistent volume to store data that needs to survive to a restart.
    template.openshift.io/documentation-url: <need_info_from_Geoffrey>
    template.openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: "false"
  name: rhdm71-optaweb-externaldb
labels:
  template: rhdm71-optaweb-externaldb
  rhdm: "1.0"
message: A new ephemeral Business Automation Employee Rostering Optimizer application using an external DB has been created in your project.
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: myapp
  required: true
- displayName: Employee Rostering Optimizer Custom http Route Hostname
  description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-optaweb-<project>.<default-domain-suffix>'
  name: OPTAWEB_SERVER_HOSTNAME_HTTP
  required: false
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
- displayName: ImageStream Tag
  description: A named pointer to an image in an image stream. Default is "1.0".
  name: IMAGE_STREAM_TAG
  value: "1.0"
  required: false
- displayName: optaweb rostering persistence Dialect
  description: optaweb rostering server persistence dialect 
  name: OPTAWEB_ROSTERING_PERSISTENCE_DIALECT
  required: true
- displayName: optaweb rostering persistence Datasource
  description: optaweb rostering server persistence datasource for persistence.xml 
  name: OPTAWEB_ROSTERING_PERSISTENCE_DATASOURCE
  example: java:/jboss/datasources/optaweb
  required: true
- description: Database name
  displayName: Database Name
  name: RHDM_EXTERNALDB_DATABASE
  required: true
- description: Database user name
  displayName: Database Username
  name: RHDM_EXTERNALDB_USERNAME
  required: true
- description: Database user password
  displayName: Database Password
  name: RHDM_EXTERNALDB_PASSWORD
  value: '1'
  required: true
- description: Database driver
  displayName: Database driver
  example: mysql
  name: RHDM_EXTERNALDB_DRIVER
  required: true
- displayName: KIE Server External Database Driver Type
  description: KIE execution server external database driver type, applicable only for DB2, possible values are 4 (default) or 2
  name: RHDM_EXTERNALDB_DRIVER_TYPE
  example: "4"
  required: false
- description: XA Connection URL
  displayName: XA Connection URL
  name: RHDM_XA_CONNECTION_PROPERTY_URL
  required: false
- description: Database service host name
  displayName: Database service host
  name: RHDM_SERVICE_HOST
  required: false
- description: Database service port number
  displayName: Database service port
  name: RHDM_SERVICE_PORT
  required: false
- description: This parameter allows to configure datasource or xa-datasource
  displayName: Database datasource / xa-datasource
  name: NON_XA_DATASOURCE
  value: "true"
  required: false
- displayName: Datasource Minimum Pool Size
  description: Sets xa-pool/min-pool-size for the configured datasource.
  name: DB_MIN_POOL_SIZE
  required: false
- displayName: Datasource Maximum Pool Size
  description: Sets xa-pool/max-pool-size for the configured datasource.
  name: DB_MAX_POOL_SIZE
  required: false
- displayName: Datasource Transaction Isolation
  description: Sets transaction-isolation for the configured datasource.
  name: DB_TX_ISOLATION
  required: false
- displayName: Decision Manager Employee Rostering Optimizer Memory Limit
  description: Decision Manager Employee Rostering Optimizer memory limit
  name: OPTAWEB_EMPLOYEE_ROSTERING_MEMORY_LIMIT
  value: 2Gi
  required: false
objects:
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "${APPLICATION_NAME}-optaweb"
  metadata:
    name: "${APPLICATION_NAME}-optaweb"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: The execution server web server's http port.
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-optaweb-http"
  metadata:
    name: "${APPLICATION_NAME}-optaweb"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: Route for execution server's http service.
  spec:
    host: "${OPTAWEB_SERVER_HOSTNAME_HTTP}"
    to:
      name: "${APPLICATION_NAME}-optaweb"
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: optaweb-service-account
    labels:
      application: "${APPLICATION_NAME}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-optaweb"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}-optaweb"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: "rhdm71-optaweb-openshift:${IMAGE_STREAM_TAG}"
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}-optaweb"
    template:
      metadata:
        name: "${APPLICATION_NAME}-optaweb"
        labels:
          deploymentConfig: "${APPLICATION_NAME}-optaweb"
          application: "${APPLICATION_NAME}"
      spec:
        serviceAccountName: optaweb-service-account
        terminationGracePeriodSeconds: 60
        containers:
        - name: "${APPLICATION_NAME}-optaweb"
          image: rhdm70-optaweb-openshift
          imagePullPolicy: Always
          resources:
            limits:
              memory: "${OPTAWEB_EMPLOYEE_ROSTERING_MEMORY_LIMIT}"
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "curl --fail --silent -u '${KIE_ADMIN_USER}:${KIE_ADMIN_PWD}' http://localhost:8080/swagger/index.html"
            initialDelaySeconds: 180
            timeoutSeconds: 2
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "curl --fail --silent -u '${KIE_ADMIN_USER}:${KIE_ADMIN_PWD}' http://localhost:8080/swagger/index.html"
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 6
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: OPTAWEB_ROSTERING_PERSISTENCE_DIALECT
            value: "${OPTAWEB_ROSTERING_PERSISTENCE_DIALECT}"
          - name: OPTAWEB_ROSTERING_PERSISTENCE_DATASOURCE
            value: "${OPTAWEB_ROSTERING_PERSISTENCE_DATASOURCE}"
          - name: DATASOURCES
            value: "RHDM"
          - name: RHDM_JNDI
            value: "${OPTAWEB_ROSTERING_PERSISTENCE_DATASOURCE}"
          - name: KIE_SERVER_PERSISTENCE_DIALECT
            value: "${OPTAWEB_ROSTERING_PERSISTENCE_DIALECT}"
          - name: RHDM_DRIVER
            value: "${RHDM_EXTERNALDB_DRIVER}"
          - name: RHDM_DRIVER_TYPE
            value: "${RHDM_EXTERNALDB_DRIVER_TYPE}"
          - name: RHDM_USERNAME
            value: "${RHDM_EXTERNALDB_USERNAME}"
          - name: RHDM_PASSWORD
            value: "${RHDM_EXTERNALDB_PASSWORD}"
          - name: RHDM_XA_CONNECTION_PROPERTY_URL
            value: "${RHDM_XA_CONNECTION_PROPERTY_URL}"
          - name: RHDM_SERVICE_HOST
            value: "${RHDM_SERVICE_HOST}"
          - name: RHDM_SERVICE_PORT
            value: "${RHDM_SERVICE_PORT}"
          - name: RHDM_DATABASE
            value: "${RHDM_EXTERNALDB_DATABASE}"
          - name: RHDM_JTA
            value: "true"
          - name: RHDM_NONXA
            value: "${NON_XA_DATASOURCE}"
          - name: DB_MIN_POOL_SIZE
            value: "${DB_MIN_POOL_SIZE}"
          - name: DB_MAX_POOL_SIZE
            value: "${DB_MAX_POOL_SIZE}"
          - name: DB_TX_ISOLATION
            value: "${DB_TX_ISOLATION}"
