kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-jboss
    tags: rhdm,jboss,kieserver,basic
    version: "1.0"
    openshift.io/display-name: Red Hat Decision Manager KIE server 7.1 S2I Ephemeral (no https)
    openshift.io/provider-display-name: Red Hat, Inc.
    description: Application template for Red Hat Decision Manager KIE server 7.1 application built using S2I.
    template.openshift.io/long-description: This template defines resources needed to execute Rules on Red Hat Decision Manager KIE server 7.1 by providing an application's source code to be built by the S2I, including a build configuration, application deployment configuration and insecure http communication.
    template.openshift.io/documentation-url: https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.1/html/deploying_red_hat_decision_manager_on_red_hat_openshift_container_platform/
    template.openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: "false"
  name: rhdm71-kieserver-basic-s2i
labels:
  template: rhdm71-kieserver-basic-s2i
  rhdm: "1.0"
message: |-
          A new Decision Manager KIE server application has been created in your project. This deployment
          does not include HTTPS support. The username/password for calls to the Decision Server is

              Username: ${KIE_SERVER_USER}
              Password: ${KIE_SERVER_PWD}

          Only stateless API calls to the Decision Server are supported.
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: myapp
  required: true
- displayName: KIE Admin User
  description: KIE administrator username. Use this user account to manage the Decision Server using administrative 
    API calls.
  name: KIE_ADMIN_USER
  value: adminUser
  required: false
- displayName: KIE Admin Password
  description: KIE administrator password
  name: KIE_ADMIN_PWD
  from: "[a-zA-Z]{6}[0-9]{1}!"
  generate: expression
  required: false
- displayName: KIE Server User
  description: KIE server user name. Use this user account for API calls to the Decision Server. 
    (Sets the org.kie.server.user system property).
  name: KIE_SERVER_USER
  value: executionUser
  required: false
- displayName: KIE Server Password
  description: KIE server password (sets the org.kie.server.pwd system property).
  name: KIE_SERVER_PWD
  from: "[a-zA-Z]{6}[0-9]{1}!"
  generate: expression
  required: false
- displayName: KIE Server ID
  description: Decision server identifier. Determines the template ID in Decision Central or controller. If this parameter is left blank, it is set using the $HOSTNAME environment variable or a random value. (Sets the org.kie.server.id system property).
  name: KIE_SERVER_ID
  value: ''
  required: false
- displayName: KIE Server Bypass Auth User
  description: KIE server bypass auth user. If this parameter is set to true, the Decision Server accepts
   API calls without user account authorization. (Sets the org.kie.server.bypass.auth.user system property).
  name: KIE_SERVER_BYPASS_AUTH_USER
  value: 'false'
  required: false
- displayName: KIE MBeans
  description: KIE server MBeans enabled/disabled. These MBeans provide monitoring information. (Sets the 
    kie.mbeans and kie.scanner.mbeans system properties).
  name: KIE_MBEANS
  value: enabled
  required: false
- displayName: Drools Server Filter Classes
  description: KIE server class filtering. When this parameter is set to true, the Decision Server extension 
    accepts custom classes annotated by the XmlRootElement or Remotable annotations only. Setting to true is preferable 
    for performance, but some custom decision services might require false. (Sets the org.drools.server.filter.classes
    system property).
  name: DROOLS_SERVER_FILTER_CLASSES
  value: 'true'
  required: false
- displayName: Decision Server Custom http Route Hostname
  description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-execserv-<project>.<default-domain-suffix>'
  name: KIE_SERVER_HOSTNAME_HTTP
  value: ''
  required: false
- displayName: KIE Server Container Deployment
  description: 'KIE Server Container deployment configuration in format: containerId=groupId:artifactId:version|c2=g2:a2:v2. 
    This information identifies the decision service (KJAR file) that is built from your source. You can provide two 
    or more KJAR files using the `|` separator, for example: `containerId=groupId:artifactId:version|c2=g2:a2:v2`. 
    The Maven build process must produce all these files from the source in the Git repository.'
  name: KIE_SERVER_CONTAINER_DEPLOYMENT
  value: rhdm-kieserver-hellorules=org.openshift.quickstarts:rhdm-kieserver-hellorules:1.4.0-SNAPSHOT
  required: false
- displayName: Git Repository URL
  description: The URI for the Git repository containing the source for your decision service.
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/jboss-container-images/rhdm-7-openshift-image.git
  required: true
- displayName: Git Reference
  description: Git branch/tag reference for the source of your decision service.
  name: SOURCE_REPOSITORY_REF
  value: rhdm71-dev
  required: false
- displayName: Context Directory
  description: Location of the module to build (pom.xml file) in the Git project. Empty for root project directory.
  name: CONTEXT_DIR
  value: quickstarts/hello-rules/hellorules
  required: false
- displayName: Github Webhook Secret
  description: GitHub trigger secret.
  name: GITHUB_WEBHOOK_SECRET
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- displayName: Generic Webhook Secret
  description: Generic build trigger secret.
  name: GENERIC_WEBHOOK_SECRET
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    Modify this setting only if you have installed the ImageStreams in a different 
    namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
- displayName: ImageStream Tag
  description: A named pointer to an image in an image stream. Default is "1.0".
  name: IMAGE_STREAM_TAG
  value: "1.0"
  required: false
- displayName: Maven mirror URL
  description: Maven mirror to use for S2I builds. If the Maven build of your decision service pulls packages 
    from a Maven repository, you can set this parameter. In this case, the build process will pull packages 
    from the mirror repository instead of the configured original repository.
  name: MAVEN_MIRROR_URL
  value: ''
  required: false
- displayName: Maven repository URL
  description: Fully qualified URL to a Maven repository.
  name: MAVEN_REPO_URL
  required: false
- displayName: Maven repository username
  description: Username to access the Maven repository, if required.
  name: MAVEN_REPO_USERNAME
  required: false
- displayName: Maven repository password
  description: Password to access the Maven repository, if required.
  name: MAVEN_REPO_PASSWORD
  required: false
- displayName: Name of the Maven service hosted by Decision Central
  description: The service name for the optional decision central, where it can be reached, to allow service lookups (for maven repo usage), if required
  name: DECISION_CENTRAL_MAVEN_SERVICE
  example: "myapp-rhdmcentr"
  required: false
- displayName: Username for the Maven service hosted by Decision Central
  description: Username to access the Maven service hosted by Decision Central inside EAP.
  name: DECISION_CENTRAL_MAVEN_USERNAME
  example: "mavenUser"
  required: false
- displayName: Password for the Maven service hosted by Decision Central
  description: Password to access the Maven service hosted by Decision Central inside EAP.
  name: DECISION_CENTRAL_MAVEN_PASSWORD
  example: "maven1!"
  required: false
- description: The directory or several directories within the project that contains the required binary files (KJAR files 
   and any other necessary files) after a successful Maven build. Files from the artefact directory are copied
   into the deployment folder. Use a comma (,) to separate multiple directories. If this parameter is not specified, all 
   archives in /target are copied.
  name: ARTIFACT_DIR
  displayName: Artifact Directory
  value: ''
  required: false
- displayName: KIE server Container Memory Limit
  description: KIE server Container memory limit
  name: EXCECUTION_SERVER_MEMORY_LIMIT
  value: 1Gi
  required: false
objects:
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "${APPLICATION_NAME}-kieserver"
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: The KIE server web server's http port.
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-kieserver-http"
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: Route for KIE server's http service.
  spec:
    host: "${KIE_SERVER_HOSTNAME_HTTP}"
    to:
      name: "${APPLICATION_NAME}-kieserver"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      # wait-for-ready used on BuildConfig ensures that template instantiation
      # will fail immediately if build fails
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Source
      sourceStrategy:
        env:
        - name: KIE_SERVER_CONTAINER_DEPLOYMENT
          value: "${KIE_SERVER_CONTAINER_DEPLOYMENT}"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_DIR
          value: "${ARTIFACT_DIR}"
        forcePull: true
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: "rhdm71-kieserver-openshift:${IMAGE_STREAM_TAG}"
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}-kieserver:latest"
    triggers:
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    - type: Generic
      generic:
        secret: "${GENERIC_WEBHOOK_SECRET}"
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}-kieserver"
        from:
          kind: ImageStream
          name: "${APPLICATION_NAME}-kieserver"
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}-kieserver"
    template:
      metadata:
        name: "${APPLICATION_NAME}-kieserver"
        labels:
          deploymentConfig: "${APPLICATION_NAME}-kieserver"
          application: "${APPLICATION_NAME}"
      spec:
        terminationGracePeriodSeconds: 60
        containers:
        - name: "${APPLICATION_NAME}-kieserver"
          image: "${APPLICATION_NAME}-kieserver"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "${EXCECUTION_SERVER_MEMORY_LIMIT}"
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "curl --fail --silent -u '${KIE_ADMIN_USER}:${KIE_ADMIN_PWD}' http://localhost:8080/services/rest/server/healthcheck"
            initialDelaySeconds: 180
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "curl --fail --silent -u '${KIE_ADMIN_USER}:${KIE_ADMIN_PWD}' http://localhost:8080/services/rest/server/readycheck"
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 6
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: DROOLS_SERVER_FILTER_CLASSES
            value: "${DROOLS_SERVER_FILTER_CLASSES}"
          - name: KIE_ADMIN_PWD
            value: "${KIE_ADMIN_PWD}"
          - name: KIE_ADMIN_USER
            value: "${KIE_ADMIN_USER}"
          - name: KIE_MBEANS
            value: "${KIE_MBEANS}"
          - name: KIE_SERVER_BYPASS_AUTH_USER
            value: "${KIE_SERVER_BYPASS_AUTH_USER}"
          - name: KIE_SERVER_ID
            value: "${KIE_SERVER_ID}"
          - name: KIE_SERVER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KIE_SERVER_CONTAINER_DEPLOYMENT
            value: "${KIE_SERVER_CONTAINER_DEPLOYMENT}"
          - name: KIE_SERVER_PWD
            value: "${KIE_SERVER_PWD}"
          - name: KIE_SERVER_USER
            value: "${KIE_SERVER_USER}"
          - name: MAVEN_REPOS
            value: "RHDMCENTR,EXTERNAL"
          - name: RHDMCENTR_MAVEN_REPO_SERVICE
            value: "${DECISION_CENTRAL_MAVEN_SERVICE}"
          - name: RHDMCENTR_MAVEN_REPO_PATH
            value: "/maven2/"
          - name: RHDMCENTR_MAVEN_REPO_USERNAME
            value: "${DECISION_CENTRAL_MAVEN_USERNAME}"
          - name: RHDMCENTR_MAVEN_REPO_PASSWORD
            value: "${DECISION_CENTRAL_MAVEN_PASSWORD}"
          - name: EXTERNAL_MAVEN_REPO_URL
            value: "${MAVEN_REPO_URL}"
          - name: EXTERNAL_MAVEN_REPO_USERNAME
            value: "${MAVEN_REPO_USERNAME}"
          - name: EXTERNAL_MAVEN_REPO_PASSWORD
            value: "${MAVEN_REPO_PASSWORD}"
