kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template for Red Hat Decision Manager Employee Rostering Business Optimizer 7.0 which uses an external DB.
    iconClass: icon-jboss
    tags: rhdm,jboss,xpaas
    version: 1.4.0
    openshift.io/display-name: Red Hat Decision Manager Employee Rostering Business Optimizer 7.0 unmanaged Employee Rostering Business Optimizer which uses an external DB
  name: rhdm70-optashift-externaldb
labels:
  template: rhdm70-optashift-externaldb
  xpaas: 1.4.0
message: A new Business Automation Employee Rostering Business Optimizer application using an external DB has been created in your project. 
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: myapp
  required: true
- displayName: Employee Rostering Business Optimizer Custom http Route Hostname
  description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-optashift-<project>.<default-domain-suffix>'
  name: EXECUTION_SERVER_HOSTNAME_HTTP
  value: ''
  required: false
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
- displayName: ImageStream Tag
  description: A named pointer to an image in an image stream. Default is "1.0".
  name: IMAGE_STREAM_TAG
  value: "1.0"
  required: false
- displayName: "Datasource Minimum Pool Size"
  description: "Sets xa-pool/min-pool-size for the configured datasource."
  name: DB_MIN_POOL_SIZE
  required: false
- displayName: "Datasource Maximum Pool Size"
  description: "Sets xa-pool/max-pool-size for the configured datasource."
  name: DB_MAX_POOL_SIZE
  required: false
- displayName: "Datasource Transaction Isolation"
  description: "Sets transaction-isolation for the configured datasource."
  name: DB_TX_ISOLATION
  required: false
- displayName: Optashift rostering persistence Dialect
  description: Optashift rostering server persistence dialect 
  name: OPTASHIFT_ROSTERING_PERSISTENCE_DIALECT
  value: ''
  required: false
- displayName: Optashift rostering persistence Datasource
  description: Optashift rostering server persistence datasource for persistence.xml 
  name: OPTASHIFT_ROSTERING_PERSISTENCE_DATASOURCE
  value: ''
  required: false
- description: Database name
  displayName: Database Name
  name: DBE_DATABASE
  required: true
- description: Database user name
  displayName: Database Username
  name: DBE_USERNAME
  required: true
- description: Database user password
  displayName: Database Password
  name: DBE_PASSWORD
  required: true
- description: Database driver, e.g. postgresql, mysql
  displayName: Database driver
  name: DBE_DRIVER
  required: true
  value: mysql  
- description: Database service host name
  displayName: Database service host
  name: DBE_SERVICE_HOST
  required: true
- description: Database service port number
  displayName: Database service port
  name: DBE_SERVICE_PORT
  required: true
- description: This parameter allows to configure datasource or xa-datasource
  displayName: Database datasource / xa-datasource
  name: NON_XA_DATASOURCE
  value: "true"
objects:
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "${APPLICATION_NAME}-optashift"
  metadata:
    name: "${APPLICATION_NAME}-optashift"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: The execution server web server's http port.
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-optashift-http"
  metadata:
    name: "${APPLICATION_NAME}-optashift"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: Route for execution server's http service.
  spec:
    host: "${EXECUTION_SERVER_HOSTNAME_HTTP}"
    to:
      name: "${APPLICATION_NAME}-optashift"
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: optashift-service-account
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-optashift"
    labels:
      application: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}-optashift"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: "rhdm70-optashift-openshift:${IMAGE_STREAM_TAG}"
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}-optashift"
    template:
      metadata:
        name: "${APPLICATION_NAME}-optashift"
        labels:
          deploymentConfig: "${APPLICATION_NAME}-optashift"
          application: "${APPLICATION_NAME}"
      spec:
        serviceAccountName: optashift-service-account
        terminationGracePeriodSeconds: 60
        containers:
        - name: "${APPLICATION_NAME}-optashift"
          image: rhdm70-optashift-openshift
          imagePullPolicy: Always
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: OPTASHIFT_ROSTERING_PERSISTENCE_DIALECT
            value: "${OPTASHIFT_ROSTERING_PERSISTENCE_DIALECT}"
          - name: OPTASHIFT_ROSTERING_PERSISTENCE_DATASOURCE
            value: "${OPTASHIFT_ROSTERING_PERSISTENCE_DATASOURCE}"
          - name: TX_DATABASE_PREFIX_MAPPING
            value: "DBE"
          - name: DB_MIN_POOL_SIZE
            value: "${DB_MIN_POOL_SIZE}"
          - name: DB_MAX_POOL_SIZE
            value: "${DB_MAX_POOL_SIZE}"
          - name: DB_TX_ISOLATION
            value: "${DB_TX_ISOLATION}"          
          - name: DATASOURCES
            value: "DBE"
          - name: DBE_USERNAME
            value: "${DBE_USERNAME}"
          - name: DBE_PASSWORD
            value: "${DBE_PASSWORD}"
          - name: DBE_DATABASE
            value: "${DBE_DATABASE}"
          - name: DBE_DRIVER
            value: "${DBE_DRIVER}"
          - name: DBE_SERVICE_HOST
            value: "${DBE_SERVICE_HOST}"
          - name: DBE_SERVICE_PORT
            value: "${DBE_SERVICE_PORT}"
          - name: NON_XA_DATASOURCE
            value: "${NON_XA_DATASOURCE}"


